# 평균구하기 without NumPy

In [6]:
## DJ's version

total = 0
count = 0

while True:
    a = input()
    if a == "":
        break
    try:
        a = float(a)
    except:
        print("Not a number!")
        a = float(input())
    total = total + a
    count += 1

print("the average is :", total/count)


ZeroDivisionError: division by zero

In [5]:
total = 0
count = 0
numbers = input("Enter a number :  (<Enter Key> to quit)")
while numbers != "":
    try:
        x = float(numbers)
        count += 1
        total = total + x
    except ValueError:
        print('NOT a number! Ignored..')
    numbers = input("Enter a number :  (<Enter Key> to quit)")
avg = total / count
print("\n average is", avg)

Enter a number :  (<Enter Key> to quit)


ZeroDivisionError: division by zero

### 4-3. 배열은 가까이에~ 기본 통계 데이터를 계산해 볼까? (2) 배열을 활용한 평균, 표준편차, 중앙값 계산

In [ ]:
# 2개 이상의 숫자를 입력받아 리스트에 저장하는 함수
def numbers():
    X=[]    # X에 빈 리스트를 할당합니다.
    while True:
        number = input("Enter a number (<Enter key> to quit)") 
        while number !="":
            try:
                x = float(number)
                X.append(x)    # float형으로 변환한 숫자 입력을 리스트에 추가합니다.
            except ValueError:
                print('>>> NOT a number! Ignored..')
            number = input("Enter a number (<Enter key> to quit)")
        if len(X) > 1:  # 저장된 숫자가 2개 이상일 때만 리턴합니다.
            return X

X=numbers()

print('X :', X)

In [22]:
#def numbers():


# get numbers by input, loop
# within the loop, append the number to the list
# if it's not a number, print a warning and do not break
# continue until a user press an enter key


def numbers():
    X = []
    x = input("Enter a number (<Enter key> to quit)")
    while x != "":
        try:
            x = float(x)
            X.append(x)
        except:
            print("Not a number")
        if x == "":
            break
        x = input("Enter a number (<Enter key> to quit)")
    if len(X) > 1:
        return X
    else:
        return "No element"

In [23]:
numbers() 

Enter a number (<Enter key> to quit)


'No element'

In [17]:
X = numbers()

Enter a number (<Enter key> to quit)1
Enter a number (<Enter key> to quit)2
Enter a number (<Enter key> to quit)3
Enter a number (<Enter key> to quit)4
Enter a number (<Enter key> to quit)5
Enter a number (<Enter key> to quit)


In [19]:
X

[1.0, 2.0, 3.0, 4.0, 5.0]

In [21]:
numbers()

Enter a number (<Enter key> to quit)


[]

In [24]:
import array as arr

mylist = [1, 2, 3]   # 이것은 파이썬 built-in list입니다. 
print(type(mylist))

mylist.append('4')  # mylist의 끝에 character '4'를 추가합니다. 
print(mylist)

mylist.insert(1, 5)  # mylist의 두번째 자리에 5를 끼워넣습니다.
print(mylist)

myarray = arr.array('i', [1, 2, 3])   # 이것은 array입니다. import array를 해야 쓸 수 있습니다.
print(type(myarray))

# 아래 라인의 주석을 풀고 실행하면 에러가 납니다.
#myarray.append('4')    # myarray의 끝에 character '4'를 추가합니다. 
print(myarray)

myarray.insert(1, 5)    # myarray의 두번째 자리에 5를 끼워넣습니다.
print(myarray)

<class 'list'>
[1, 2, 3, '4']
[1, 5, 2, 3, '4']
<class 'array.array'>
array('i', [1, 2, 3])
array('i', [1, 5, 2, 3])


In [25]:
total = 0.0
for i in range(len(X)):
    total = total + X[i]
mean = total / len(X)

print('sum of X: ', total)

sum of X:  15.0


In [39]:
# 중앙값 return 하는 코드
# list 개수가 홀수일 경우 : n/2의 반올림 번째꺼가 중앙값
# list 개수가 짝수일 경우 : (n/2 + n/2+1)/2가 중앙값

def median(nums):
    nums.sort()
    if len(nums) % 2 == 0: # 짝수일 경우
        count = len(nums)
        inde1 = int(count/2)
        inde2 = inde1+1
        return (nums[inde1] + nums[inde2])/2
    elif len(nums) % 2 == 1: # 홀수일 경우
        count = len(nums)
        inde = int(count/2) + 1
        return nums[inde-1]
    else:
        return "No element"

In [40]:
a = [1,2,6,7,3,5,7,8,9,64,4,53,5]

In [41]:
sum(a)

174

In [42]:
a.sort()

In [43]:
a

[1, 2, 3, 4, 5, 5, 6, 7, 7, 8, 9, 53, 64]

In [46]:
len(a)

13

In [45]:
median(a)

6

In [47]:
sum(a) // 2

87

In [48]:
# Aiffel version

In [49]:
def median(nums):  		# nums : 리스트를 지정하는 매개변수
    nums.sort()					# sort()로 리스트를 순서대로 정렬
    size = len(nums)
    p = size // 2
    if size % 2 == 0:		   # 리스트의 개수가 짝수일때 
        pr = p                         # 4번째 값
        pl = p-1                      # 3번째 값
        mid= float((nums[pl]+nums[pr])/2)    
    else:								# 리스트의 개수가 홀수일때
        mid = nums[p]
    return mid

print('X :', X)
median(X)						# 매개변수의 값으로 X를 사용함

X : [1.0, 2.0, 3.0, 4.0, 5.0]


3.0

In [50]:
median(a)

6

### 표준편차 구하는 코드

In [51]:
def means(nums):
    total = 0.0
    for i in range(len(nums)):
        total = total + nums[i]
    return total / len(nums)

means(X)

3.0

In [57]:
def std(li):
    new_li = []
    for i in li:
        new_li.append(((i - means(li)) **2)

    sum(new_li)/(len(new_li)-1) ** 0.5

SyntaxError: invalid syntax (<ipython-input-57-bb7f1ecc0dd8>, line 6)

## 6) 전체 코드 : main()함수
위에 구현한 코드를 순서대로 사용해 보겠습니다.

우리가 구현하고자 하는 값은 사용자가 입력한 숫자들에 대한 평균값, 중앙값, 표준편차입니다.
우선 사용자가 입력한 숫자를 배열(리스트)로 만듭니다.
각 숫자의 평균값과 중앙값을 구합니다.
각 숫자의 표준편차를 구합니다.
각 함수들은 다 구현했죠? main함수로 구현해 보면 다음과 같습니다.

In [59]:
def numbers():
    X=[]
    while True:
        number = input("Enter a number (<Enter key> to quit)") 
        while number !="":
            try:
                x = float(number)
                X.append(x)
            except ValueError:
                print('>>> NOT a number! Ignored..')
            number = input("Enter a number (<Enter key> to quit)")
        if len(X) > 1:
            return X

def median(nums): 
    nums.sort()
    size = len(nums)
    p = size // 2
    if size % 2 == 0:
        pr = p
        pl = p-1
        mid = float((nums[pl]+nums[pr])/2)
    else:
        mid = nums[p]
    return mid

def means(nums):
    total = 0.0
    for i in range(len(nums)):
        total = total + nums[i]
    return total / len(nums)

def std_dev(nums, avg):
   texp = 0.0
   for i in range(len(nums)):
       texp = texp + (nums[i] - avg) ** 2
   return (texp/(len(nums)-1)) ** 0.5

def main():
    X = numbers()
    med = median(X)
    avg = means(X)
    std = std_dev(X, avg)
    print("당신이 입력한 숫자{}의 ".format(X))
    print("중앙값은{}, 평균은{}, 표준편차는{}입니다.".format(med, avg, std))

if __name__ == '__main__':
    main()

Enter a number (<Enter key> to quit)1
Enter a number (<Enter key> to quit)2
Enter a number (<Enter key> to quit)3
Enter a number (<Enter key> to quit)4
Enter a number (<Enter key> to quit)5
Enter a number (<Enter key> to quit)6
Enter a number (<Enter key> to quit)7
Enter a number (<Enter key> to quit)8
Enter a number (<Enter key> to quit)9
Enter a number (<Enter key> to quit)10
Enter a number (<Enter key> to quit)100
Enter a number (<Enter key> to quit)200
Enter a number (<Enter key> to quit)300
Enter a number (<Enter key> to quit)400
Enter a number (<Enter key> to quit)500
Enter a number (<Enter key> to quit)600
Enter a number (<Enter key> to quit)700
Enter a number (<Enter key> to quit)800
Enter a number (<Enter key> to quit)900
Enter a number (<Enter key> to quit)1010
Enter a number (<Enter key> to quit)2020
Enter a number (<Enter key> to quit)3030
Enter a number (<Enter key> to quit)4040
Enter a number (<Enter key> to quit)5050
Enter a number (<Enter key> to quit)6060
Enter a numbe

In [60]:
conda list | grep numpy

numpy                     1.17.2           py37h99e6662_0  
numpy-base                1.17.2           py37h6575580_0  
numpydoc                  0.9.1                      py_0  

Note: you may need to restart the kernel to use updated packages.


##### 1) ndarray만들기

In [61]:
import numpy as np

# 아래 A와 B는 결과적으로 같은 ndarray 객체를 생성합니다. 
A = np.arange(5)
B = np.array([0,1,2,3,4])  # 파이썬 리스트를 numpy ndarray로 변환

# 하지만 C는 좀 다를 것입니다. 
C = np.array([0,1,2,3,'4'])

# D도 A, B와 같은 결과를 내겠지만, B의 방법을 권합니다. 
D = np.ndarray((5,), np.int64, np.array([0,1,2,3,4]))

print(A)
print(type(A))
print("--------------------------")
print(B)
print(type(B))
print("--------------------------")
print(C)
print(type(C))
print("--------------------------")
print(D)
print(type(D))

[0 1 2 3 4]
<class 'numpy.ndarray'>
--------------------------
[0 1 2 3 4]
<class 'numpy.ndarray'>
--------------------------
['0' '1' '2' '3' '4']
<class 'numpy.ndarray'>
--------------------------
[0 1 2 3 4]
<class 'numpy.ndarray'>


In [62]:
A = np.arange(10).reshape(2, 5)   # 길이 10의 1차원 행렬을 2X5 2차원 행렬로 바꿔봅니다.

print("행렬의 모양:", A.shape)
print("행렬의 축 개수:", A.ndim)
print("행렬 내 원소의 개수:", A.size)

행렬의 모양: (2, 5)
행렬의 축 개수: 2
행렬 내 원소의 개수: 10


In [63]:
A

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [67]:
A.size

10

### 3) type

In [68]:
A= np.arange(6).reshape(2, 3)
print(A)
print(A.dtype)
print(type(A))
print("-------------------------")

B = np.array([0, 1, 2, 3, 4, 5])  
print(B)
print(B.dtype)
print(type(B))
print("-------------------------")

C = np.array([0, 1, 2, 3, '4', 5])
print(C)
print(C.dtype)
print(type(C))
print("-------------------------")

D = np.array([0, 1, 2, 3, [4, 5], 6])  # 이런 ndarray도 만들어질까요?
print(D)
print(D.dtype)
print(type(D))

[[0 1 2]
 [3 4 5]]
int64
<class 'numpy.ndarray'>
-------------------------
[0 1 2 3 4 5]
int64
<class 'numpy.ndarray'>
-------------------------
['0' '1' '2' '3' '4' '5']
<U21
<class 'numpy.ndarray'>
-------------------------
[0 1 2 3 list([4, 5]) 6]
object
<class 'numpy.ndarray'>


In [69]:
C = np.array([0,1,2,3,'4',5])
print(C[0])
print(type(C[0]))
print(C[4])
print(type(C[4]))
print("------------------------------")

D = np.array([0,1,2,3,[4,5],6])
print(D[0])
print(type(D[0]))
print(D[4])
print(type(D[4]))

0
<class 'numpy.str_'>
4
<class 'numpy.str_'>
------------------------------
0
<class 'int'>
[4, 5]
<class 'list'>


### 4) 특수행렬

In [70]:
# 단위행렬
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [71]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [72]:
# 0 행렬
np.zeros([2,3])

array([[0., 0., 0.],
       [0., 0., 0.]])

In [74]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [75]:
# 1행렬
np.ones([3,3])

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [77]:
np.ones((5,6))

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

### 5) 브로드캐스트

In [78]:
A = np.arange(9).reshape(3,3)
A

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [79]:
A *2

array([[ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16]])

In [80]:
A + 2

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10]])

In [81]:
# 3 X 3 행렬에 1 X 3 행렬을 더했을 때
A = np.arange(9).reshape(3,3)
B = np.array([1, 2, 3])
print("A:", A)
print("B:", B)
print("\nA+B:", A+B)

A: [[0 1 2]
 [3 4 5]
 [6 7 8]]
B: [1 2 3]

A+B: [[ 1  3  5]
 [ 4  6  8]
 [ 7  9 11]]


In [82]:
# 3 X 3 행렬에 3 X 1 행렬을 더했을 때
A = np.arange(9).reshape(3,3)
C = np.array([[1], [2], [3]])
print("A:", A)
print("C:", C)
print("\nA+C:", A+C)

A: [[0 1 2]
 [3 4 5]
 [6 7 8]]
C: [[1]
 [2]
 [3]]

A+C: [[ 1  2  3]
 [ 5  6  7]
 [ 9 10 11]]


In [83]:
print([1,2]+[3,4])
print([1,2]+3)

[1, 2, 3, 4]


TypeError: can only concatenate list (not "int") to list

In [84]:
print(np.array([1,2])+np.array([3,4]))
print(np.array([1,2])+3)

[4 6]
[4 5]


In [85]:
# 3 X 3 행렬의 첫번째 행을 구해 봅시다. 
A = np.arange(9).reshape(3,3)
print("A:", A)
B = A[0]
print("B:", B)

A: [[0 1 2]
 [3 4 5]
 [6 7 8]]
B: [0 1 2]


In [88]:
A[2]

array([6, 7, 8])

In [89]:
A[2,1]

7

In [90]:
# 0, 1을 인덱싱 하면 A의 첫번째 행에서 두번째 값을 참조합니다.
# 아래 두 결과는 정확히 같습니다.
print(A[0, 1])
print(B[1])

1
1


In [91]:
# 슬라이싱도 비슷합니다.
A[:-1]

array([[0, 1, 2],
       [3, 4, 5]])

In [95]:
A[:,-1]

array([2, 5, 8])

In [96]:
# 이 슬라이싱의 결과는 
print(A[:,2:])
print("--------------")
print(A[:,1:])
print("--------------")
print(A[:,:])
print("--------------")
# 이 슬라이싱의 결과와 동일합니다.
print(A[:,-1:])
print("--------------")
print(A[:,-2:])
print("--------------")
print(A[:,-3:])

# 위 그림과 비교해서 이해해 보세요.

[[2]
 [5]
 [8]]
--------------
[[1 2]
 [4 5]
 [7 8]]
--------------
[[0 1 2]
 [3 4 5]
 [6 7 8]]
--------------
[[2]
 [5]
 [8]]
--------------
[[1 2]
 [4 5]
 [7 8]]
--------------
[[0 1 2]
 [3 4 5]
 [6 7 8]]


### 7) random

In [97]:
# 의사 난수를 생성하는 예제입니다. 여러번 실행해 보세요.

print(np.random.random())   # 0에서 1사이의 실수형 난수 하나를 생성합니다. 

print(np.random.randint(0,10))   # 0~9 사이 1개 정수형 난수 하나를 생성합니다. 

print(np.random.choice([0,1,2,3,4,5,6,7,8,9]))   # 리스트에 주어진 값 중 하나를 랜덤하게 골라줍니다.

0.6350638254086112
1
6


In [98]:
# 무작위로 섞인 배열을 만들어 줍니다. 
# 아래 2가지는 기능면에서 동일합니다. 

print(np.random.permutation(10))   
print(np.random.permutation([0,1,2,3,4,5,6,7,8,9]))

[5 9 6 3 0 1 7 8 2 4]
[0 7 9 5 1 4 2 6 3 8]


In [103]:
z = np.random.permutation(1)
z

array([0])

In [102]:
z.size

100

In [104]:
# 아래 기능들은 어떤 분포를 따르는 변수를 임의로 표본추출해 줍니다. 

# 이것은 정규분포를 따릅니다.
print(np.random.normal(loc=0, scale=1, size=5))    # 평균(loc), 표준편차(scale), 추출개수(size)를 조절해 보세요.

# 이것은 균등분포를 따릅니다. 
print(np.random.uniform(low=-1, high=1, size=5))  # 최소(low), 최대(high), 추출개수(size)를 조절해 보세요.

[-1.03278579 -0.26525327  0.01006574  1.23090668 -2.1600001 ]
[-0.0709498   0.85662114  0.72632021  0.72500234 -0.75284683]


In [105]:
np.random.normal(loc=0, scale=1, size= 6)

array([ 0.26809518, -1.58576538,  0.48503175,  0.14003206, -0.09920626,
       -1.52077958])

In [106]:
np.random.uniform(low=1, high=2, size=5)

array([1.9291086 , 1.01853491, 1.78429087, 1.73084599, 1.44684947])

### 8) 전치행렬

In [107]:
A = np.arange(24).reshape(2,3,4)
print("A:", A)               # A는 (2,3,4)의 shape를 가진 행렬입니다. 
print("A의 전치행렬:", A.T)            
print("A의 전치행렬의 shape:", A.T.shape) # A의 전치행렬은 (4,3,2)의 shape를 가진 행렬입니다.

A: [[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
A의 전치행렬: [[[ 0 12]
  [ 4 16]
  [ 8 20]]

 [[ 1 13]
  [ 5 17]
  [ 9 21]]

 [[ 2 14]
  [ 6 18]
  [10 22]]

 [[ 3 15]
  [ 7 19]
  [11 23]]]
A의 전치행렬의 shape: (4, 3, 2)


In [108]:
A[0]

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [109]:
A[1]

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [110]:
A[0,1]

array([4, 5, 6, 7])

In [111]:
A[0,1,3]

7

In [114]:
A.T[3,1,0]

7

In [116]:
A.T[3,1]

array([ 7, 19])

In [117]:
# np.transpose는 행렬의 축을 어떻게 변환해 줄지 임의로 지정해 줄 수 있는 일반적인 행렬 전치 함수입니다. 
# np.transpose(A, (2,1,0)) 은 A.T와 정확히 같습니다.

B = np.transpose(A, (2,0,1))
print("A:", A)             # A는 (2,3,4)의 shape를 가진 행렬입니다. 
print("B:", B)             # B는 A의 3, 1, 2번째 축을 자신의 1, 2, 3번째 축으로 가진 행렬입니다.
print("B.shape:", B.shape)  # B는 (4,2,3)의 shape를 가진 행렬입니다.

A: [[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
B: [[[ 0  4  8]
  [12 16 20]]

 [[ 1  5  9]
  [13 17 21]]

 [[ 2  6 10]
  [14 18 22]]

 [[ 3  7 11]
  [15 19 23]]]
B.shape: (4, 2, 3)


In [118]:
np.transpose()

TypeError: _transpose_dispatcher() missing 1 required positional argument: 'a'

## 4-6. 끝판왕 등장! NumPy로 이 모든 걸 한방에! (3) NumPy로 기본 통계 데이터 계산해 보기


In [119]:

import numpy as np

# 6-3 스텝에서 사용하였던 함수입니다. 
def numbers():
    X = []
    number = input("Enter a number (<Enter key> to quit)") 
    # 하지만 2개 이상의 숫자를 받아야 한다는 제약조건을 제외하였습니다.
    while number != "":
        try:
            x = float(number)
            X.append(x)
        except ValueError:
            print('>>> NOT a number! Ignored..')
        number = input("Enter a number (<Enter key> to quit)")
    return X

def main():
    nums = numbers()       # 이것은 파이썬 리스트입니다. 
    num = np.array(nums)   # 리스트를 Numpy ndarray로 변환합니다.
    print("합", num.sum())
    print("평균값",num.mean())
    print("표준편차",num.std())
    print("중앙값",np.median(num))   # num.median() 이 아님에 유의해 주세요.

main()

Enter a number (<Enter key> to quit)1
Enter a number (<Enter key> to quit)2
Enter a number (<Enter key> to quit)3
Enter a number (<Enter key> to quit)4
Enter a number (<Enter key> to quit)5
Enter a number (<Enter key> to quit)6
Enter a number (<Enter key> to quit)
합 21.0
평균값 3.5
표준편차 1.707825127659933
중앙값 3.5
